import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Suspense } from "react";
import Nav from "@/app/components/Services/nav";
import { ThemeProvider } from "@/app/ThemeProvider/ThemeProviderClient"
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'gallery-web',
  description: 'Generated by Gavin Arori',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
      
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Suspense fallback="...">
          <Nav />
         </Suspense>
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
    </html>
  )
}
