import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Suspense } from "react";
import Nav from "@/app/components/Services/nav";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'gallery-web',
  description: 'Generated by Gavin Arori',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
      <Suspense fallback="...">
          <Nav />
        </Suspense>
        {children}
        </body>
    </html>
  )
}
